server :
  port : 8888

spring :
  application :
    name : configServer
  cloud :
    config :
      server :
        git :
          uri : https://github.com/DaianaServin/esp-back-i-parcial
          default-label : develop
          force-pull : true
          search-paths : ConfigData